# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qeMSUJ1nuAZGHeeDvIiRuK_VKEhkHPc8

# Pipeline dan Preprocessing
"""

import os
import re
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 1. Load Dataset
def load_formal_jobs(path):
    df = pd.read_csv(path)
    out = pd.DataFrame()
    out["job_id"] = ["FML" + str(i + 1).zfill(4) for i in range(len(df))]
    out["judul"] = df["title"].fillna("")

    # Gabungan teks untuk TF-IDF
    out["deskripsi"] = (
        df["title"].fillna("") + ". " +
        df["requirement"].fillna("") + ". " +
        df["description"].fillna("") + ". " +
        df["qualification"].fillna("")
    )
    out["kategori"] = df["type_of_work"].fillna(df["job_level"]).fillna("")
    out["sumber"] = "Formal"
    out["company"] = df.get("company", "")
    out["link"] = df.get("link", "")
    return out


def load_informal_jobs(path):
    df = pd.read_csv(path)
    out = pd.DataFrame()
    out["job_id"] = df["job_id"]
    out["judul"] = df["judul_pekerjaan"]
    out["deskripsi"] = df["judul_pekerjaan"] + ". " + df["deskripsi"]
    out["kategori"] = df["kategori_skill"]
    out["sumber"] = "Informal"
    out["company"] = "Perorangan/UMKM"
    out["link"] = ""
    return out


def load_workers(path):
    df = pd.read_csv(path)
    out = pd.DataFrame()
    out["worker_id"] = df["worker_id"]
    out["nama"] = df["name"]
    out["jenis_kelamin"] = df["gender"]
    out["skill_text"] = df["skills"].fillna("")
    return out


def build_datasets(formal_path, informal_path, worker_path, out_dir="data"):
    os.makedirs(out_dir, exist_ok=True)

    formal = load_formal_jobs(formal_path)
    informal = load_informal_jobs(informal_path)
    workers = load_workers(worker_path)

    all_jobs = pd.concat([formal, informal], ignore_index=True)
    all_jobs = all_jobs[all_jobs["judul"].str.strip() != ""]
    all_jobs = all_jobs.drop_duplicates(subset=["judul", "deskripsi"]).reset_index(drop=True)

    workers = workers[workers["skill_text"].str.strip() != ""]
    workers = workers.drop_duplicates(subset=["nama", "skill_text"]).reset_index(drop=True)

    all_jobs.to_csv(f"{out_dir}/all_jobs.csv", index=False)
    workers.to_csv(f"{out_dir}/all_workers.csv", index=False)

    print(f"[load_data] Total job: {len(all_jobs)}")
    print(f"[load_data] Total worker: {len(workers)}")
    return all_jobs, workers

# 2. Preprocessing Teks
STOPWORDS_ID = set("""
yang untuk dan atau di ke dari pada dengan ini itu adalah akan bisa dapat
para dalam sebagai oleh sudah telah juga tidak agar karena jika maka lebih
kami kita anda dia mereka saya kamu nya kan lah pun tersebut serta
membutuhkan dibutuhkan mencari dicari butuh cari kandidat pengalaman
minimal tahun bulan hari kerja gaji upah bergabung tim perusahaan
persyaratan deskripsi pekerjaan job description requirement
memiliki sederajat pendidikan min baik melakukan usia diploma staff
and in to the of a an is are with be able good responsible
bekerja slta sma smk s1 s2 mampu membuat pria wanita waktu sarjana
penuh part full time jam kerja lokasi domisili wajib diutamakan

menguasai kemampuan jujur target jawab max maksimal bidang manager
d3 s3 lulusan jurusan posisi lokasi sistem kerja bidang bidangnya
for or experience work team communication management business service
skills skill tingkat tinggi terkait standar umum ketentuan lain
""".split())


def clean_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    tokens = [w for w in text.split() if w not in STOPWORDS_ID and len(w) > 1]
    return " ".join(tokens)


def build_job_corpus(all_jobs_df):
    combined = (
        all_jobs_df["judul"].fillna("") + " " +
        all_jobs_df["kategori"].fillna("") + " " +
        all_jobs_df["deskripsi"].fillna("")
    )
    return combined.apply(clean_text)


def build_worker_corpus(workers_df):
    return workers_df["skill_text"].fillna("").apply(clean_text)

"""# Feature Extraction & Vectorization"""

import os
import re
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# 3. TF IDF

class KerjaDekatRecommender:
    def __init__(self, all_jobs_df, workers_df):
        self.jobs = all_jobs_df.reset_index(drop=True)
        self.workers = workers_df.reset_index(drop=True)

        self.job_corpus = build_job_corpus(self.jobs)
        self.worker_corpus = build_worker_corpus(self.workers)

        self.vectorizer = TfidfVectorizer(
        ngram_range=(1, 2),
        max_features=5000,
        sublinear_tf=True,
        max_df=0.3
        )

        combined_corpus = pd.concat([self.job_corpus, self.worker_corpus])
        self.vectorizer.fit(combined_corpus)

        self.job_vectors = self.vectorizer.transform(self.job_corpus)
        self.worker_vectors = self.vectorizer.transform(self.worker_corpus)

    def recommend_for_worker(self, worker_id, top_n=10):
        idx_list = self.workers.index[self.workers["worker_id"] == worker_id].tolist()
        if not idx_list:
            raise ValueError(f"worker_id '{worker_id}' tidak ditemukan")
        w_idx = idx_list[0]

        # Hitung kemiripan skill
        skill_scores = cosine_similarity(
            self.worker_vectors[w_idx], self.job_vectors
        ).flatten()

        result = self.jobs.copy()
        result["skill_score"] = (skill_scores * 100).round(2)

        top_jobs = result.sort_values("skill_score", ascending=False).head(top_n).reset_index(drop=True)

        cols = ["job_id", "judul", "sumber", "kategori", "skill_score"]
        return top_jobs[cols]

    def predict_new_worker(self, skill_text, top_n=10):
        teks_bersih = clean_text(skill_text)
        vector_baru = self.vectorizer.transform([teks_bersih])
        skill_scores = cosine_similarity(
            vector_baru, self.job_vectors
        ).flatten()

        result = self.jobs.copy()
        result["skill_score"] = (skill_scores * 100).round(2)
        top_jobs = (
            result.sort_values("skill_score", ascending=False)
            .head(top_n)
            .reset_index(drop=True)
        )

        cols = ["job_id", "judul", "sumber", "kategori", "skill_score"]
        return top_jobs[cols]

    def predict_new_job(self, judul, deskripsi, top_n=10):
        """Untuk job baru yang belum ada di database."""
        teks_bersih = clean_text(judul + " " + deskripsi)
        vector_baru = self.vectorizer.transform([teks_bersih])
        skill_scores = cosine_similarity(
            vector_baru, self.worker_vectors
        ).flatten()

        result = self.workers.copy()
        result["skill_score"] = (skill_scores * 100).round(2)
        top_workers = (
            result.sort_values("skill_score", ascending=False)
            .head(top_n)
            .reset_index(drop=True)
        )

        cols = ["worker_id", "nama", "skill_score"]
        return top_workers[cols]

    def get_top_keywords(self, top_n=20):
        feature_names = self.vectorizer.get_feature_names_out()
        sums = np.asarray(self.job_vectors.sum(axis=0)).flatten()
        top_indices = sums.argsort()[::-1][:top_n]
        return [(feature_names[i], round(sums[i], 2)) for i in top_indices]

"""# Rekomendasi Engine Match"""

all_jobs, workers = build_datasets(
    formal_path="formal_jobs_500.csv",
    informal_path="informal_jobs.csv",
    worker_path="worker_profiles (1).csv",
    out_dir="data",
)
rec = KerjaDekatRecommender(all_jobs, workers)

hasil_rekomendasi = rec.predict_new_job(
    judul="Admin Keuangan dan Kasir",
    deskripsi="Mencari staf admin yang teliti, paham pembukuan kas, dan bisa mengoperasikan Excel",
    top_n=5,
)

# Tampilkan hasilnya
print(hasil_rekomendasi)

rec.get_top_keywords(top_n=15)

# 4. Eksekusi
if __name__ == "__main__":
    # Buat dataset gabungan
    all_jobs, workers = build_datasets(
        formal_path="formal_jobs_500.csv",
        informal_path="informal_jobs.csv",
        worker_path="worker_profiles (1).csv",
        out_dir="data",
    )

    # Inisialisasi model
    rec = KerjaDekatRecommender(all_jobs, workers)

    # Uji coba rekomendasi untuk 3 worker pertama
    for wid in workers["worker_id"].head(3):
        nama = workers.loc[workers["worker_id"] == wid, "nama"].values[0]
        skill = workers.loc[workers["worker_id"] == wid, "skill_text"].values[0]
        print(f"\n=== Rekomendasi untuk {wid} - {nama} ===")
        print(f"Skill: {skill[:80]}...")
        print(rec.recommend_for_worker(wid, top_n=10).to_string(index=False))

if __name__ == "__main__":
    # 1. Load dan buat dataset gabungan
    all_jobs, workers = build_datasets(
        formal_path="formal_jobs_500.csv",
        informal_path="informal_jobs.csv",
        worker_path="worker_profiles (1).csv",
        out_dir="data",
    )

    # 2. Inisialisasi model recommender
    rec = KerjaDekatRecommender(all_jobs, workers)

    random_workers = workers.sample(n=3)

    # 4. Tampilkan hasil rekomendasi
    for _, worker_row in random_workers.iterrows():
        wid = worker_row["worker_id"]
        nama = worker_row["nama"]
        skill = worker_row["skill_text"]

        print(f"\n=== Rekomendasi untuk {wid} - {nama} ===")
        print(f"Skill: {skill[:80]}...")
        print(rec.recommend_for_worker(wid, top_n=10).to_string(index=False))

if __name__ == "__main__":
    # 1. Load data
    all_jobs, workers = build_datasets(
        formal_path="formal_jobs_500.csv",
        informal_path="informal_jobs.csv",
        worker_path="worker_profiles (1).csv",
        out_dir="data",
    )

    # 2. Inisialisasi model
    rec = KerjaDekatRecommender(all_jobs, workers)
    informal_keywords = [
        'cuci', 'setrika', 'masak', 'kebun', 'art', 'laundry',
        'tukang', 'bangunan', 'supir', 'sopir', 'kurir', 'satpam', 'security'
    ]

    # Cari worker yang teks skill-nya mengandung salah satu kata kunci di atas
    mask_informal = workers["skill_text"].str.lower().str.contains('|'.join(informal_keywords), na=False)
    informal_workers = workers[mask_informal]

    # Ambil 3 sampel worker acak dari hasil filter
    sample_informal_workers = informal_workers.sample(n=3)

    # 4. Tampilkan Hasil
    for _, worker_row in sample_informal_workers.iterrows():
        wid = worker_row["worker_id"]
        nama = worker_row["nama"]
        skill = worker_row["skill_text"]

        print(f"\n=== Rekomendasi untuk {wid} - {nama} ===")
        print(f"Skill: {skill[:100]}...")
        print(rec.recommend_for_worker(wid, top_n=10).to_string(index=False))

"""# Evaluasi"""

import numpy as np

def evaluate_recommender(recommender_system, sample_size=50, top_n=10):
    """
    Menghitung rata-rata skill_score untuk top_n rekomendasi
    dari sampel worker acak.
    """
    workers_sample = recommender_system.workers.sample(
        n=min(sample_size, len(recommender_system.workers)),
        random_state=42
    )

    all_top_scores = []

    for wid in workers_sample["worker_id"]:
        rec_df = recommender_system.recommend_for_worker(wid, top_n=top_n)
        mean_score = rec_df["skill_score"].mean()
        all_top_scores.append(mean_score)

    overall_avg = np.mean(all_top_scores)
    print(f"=== HASIL EVALUASI MODEL ===")
    print(f"Jumlah sampel worker  : {len(workers_sample)}")
    print(f"Top-N Rekomendasi     : {top_n}")
    print(f"Rata-rata Skill Score : {overall_avg:.4f}")
    return overall_avg

# Jalankan evaluasi
evaluate_recommender(rec, sample_size=50, top_n=10)

def evaluate_precision_at_k(recommender_system, sample_size=50, top_n=10, threshold=0.05):
    workers_sample = recommender_system.workers.sample(
        n=min(sample_size, len(recommender_system.workers)),
        random_state=42
    )

    precision_list = []

    for wid in workers_sample["worker_id"]:
        rec_df = recommender_system.recommend_for_worker(wid, top_n=top_n)
        # Hitung berapa banyak job dari Top-N yang skornya di atas threshold
        relevant_jobs = (rec_df["skill_score"] >= threshold).sum()
        precision = relevant_jobs / top_n
        precision_list.append(precision)

    avg_precision = np.mean(precision_list)
    print(f"=== EVALUASI PRECISION@{top_n} ===")
    print(f"Threshold Skor Relevan : {threshold}")
    print(f"Mean Precision@{top_n}    : {avg_precision * 100:.2f}%")
    return avg_precision

# Jalankan evaluasi precision
evaluate_precision_at_k(rec, sample_size=50, top_n=10, threshold=0.03)

"""# API"""

import joblib
import os

os.makedirs("artifacts", exist_ok=True)

joblib.dump(rec.vectorizer, "artifacts/tfidf_vectorizer.pkl")
joblib.dump(rec.jobs, "artifacts/jobs_data.pkl")
joblib.dump(rec.job_vectors, "artifacts/job_vectors.pkl")
joblib.dump(rec.workers, "artifacts/workers_data.pkl")
joblib.dump(rec.worker_vectors, "artifacts/worker_vectors.pkl")

print(
    "File artifacts berhasil disimpan di folder 'artifacts/'"
)

!zip -r artifacts.zip artifacts/

from google.colab import files

files.download("artifacts.zip")